- name: Get existing users
  ansible.builtin.getent:
    database: passwd

- name: Set existing users list
  ansible.builtin.set_fact:
    ansible_facts:
      existing_users: "{{ getent_passwd.keys() | list }}"