- name: Move home directory 
  ansible.builtin.command: >
    usermod -d /home/{{ new_username }} -m {{ new_username }}
  when:
    - new_username not in existing_users
    - old_username in existing_users