- name: Check crontab for each user
  ansible.builtin.shell: "crontab -l -u {{ user_to_delete }}"
  register: user_crontab
  ignore_errors: true

- name: Warn if crontab exists
  ansible.builtin.fail:
    msg: "User {{ user_to_delete }} has crontab: {{ user_crontab.stdout_lines }}"
  when: user_crontab.rc == 0

