- name: Change Linux user password
  hosts: all
  become: true
  vars:
    username: "{{ username }}"
    user_password: "{{ password }}"
  tasks:
    - name: Set user password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ user_password | password_hash('sha512') }}"
        update_password: always