- name: Change Linux user password
  tasks:
    - name: Set user password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: always